=== shahzadhussain61224/github-tibco/BW5_Quality_Analysis/Code/SharedResources/Schema/ValidateMetaDataDriven/RecordSetStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.hp.com/process/2013-04/MDD/RecordSetStructure"
	 targetNamespace="http://www.hp.com/process/2013-04/MDD/RecordSetStructure"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="recordSet" type="RecordSetStructure"/>
	<xs:complexType name="RecordStructure">
		<xs:sequence>
			<xs:element name="checkType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="checkAllPass"/>
						<xs:enumeration value="checkAnyPass"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="recordType" type="xs:string"/>
			<xs:element name="field" type="FieldStructure" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FieldStructure">
		<xs:sequence>
			<xs:element name="activityType" type="xs:string"/>
			<xs:element name="activityName" type="xs:string"/>
			<xs:element name="format" type="FieldFormat"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RecordSetStructure">
		<xs:sequence>
			<xs:element name="record" type="RecordStructure" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StringFormat">
		<xs:sequence>
			<xs:element name="maxLength" type="xs:int" minOccurs="0"/>
			<xs:element name="patterns" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="options" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FieldFormat">
		<xs:sequence>
			<xs:element name="stringFormat" type="StringFormat" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== shahzadhussain61224/github-tibco/BW5_Quality_Analysis/Code/SharedResources/XMLFiles/MDDPdRules.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<recordSet xmlns = "http://www.hp.com/process/2013-04/MDD/RecordSetStructure" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://www.hp.com/process/2013-04/MDD/RecordSetStructure ../../Schemas/ValidateMetaDataDriven/RecordSetStructure.xsd">
	<record>
		<checkType>checkAllPass</checkType>
		<description>Activity Name Validation</description>
		<recordType>Process Definition</recordType>
		<field>
			<activityType>HTTPEventSource</activityType>
			<activityName>HTTP Receiver</activityName>
			<format>
				<stringFormat>
					<maxLength>10</maxLength>
					<patterns>
							<options>^[A-Z][a-z]*( [A-Z][a-z]*)?( [1-9]*)?$</options>
					</patterns>
				</stringFormat>
			</format>
		</field>
		<field>
			<activityType>MapperActivity</activityType>
			<activityName>Map Data</activityName>
			<format>
				<stringFormat>
					<maxLength>10</maxLength>
					<patterns>
							<options>^[A-Z][a-z]*( [A-Z][a-z]*)?( [1-9]*)?$</options>
					</patterns>
				</stringFormat>
			</format>
		</field>
		<field>
			<activityType>CatchActivity</activityType>
			<activityName>Catch</activityName>
			<format>
				<stringFormat>
					<maxLength>10</maxLength>
					<patterns>
							<options>^[A-Z][a-z]*( [A-Z][a-z]*)?( [1-9]*)?$</options>
					</patterns>
				</stringFormat>
			</format>
		</field>
		<field>
			<activityType>WriteToLogActivity</activityType>
			<activityName>Log</activityName>
			<format>
				<stringFormat>
					<maxLength>1</maxLength>
					<patterns>
							<options>^[A-Z][a-z]*( [A-Z][a-z]*)?( [1-9]*)?$</options>
					</patterns>
				</stringFormat>
			</format>
		</field>
		<field>
			<activityType>processName</activityType>
			<activityName>Process Definition</activityName>
			<format>
				<stringFormat>
					<maxLength>10</maxLength>
					<patterns>
							<options>^[A-Z][a-z]*([A-Z][a-z]*)?[1-9]*$</options>
					</patterns>
				</stringFormat>
			</format>
		</field>
	</record>
</recordSet>
